[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "examplepackage"
version = "0.0.1"
description = "A super simple example package"
authors = [{ name="Your Name", email="you@example.com" }]
requires-python = ">=3.8"
